server {
  listen 8080;
  server_name _;
  client_max_body_size 2m;
  location = /commerce-api/metrics { return 404; }
  location /commerce-api/ {
    proxy_pass http://commerce-api:3210/;
    proxy_connect_timeout 3s;
    proxy_read_timeout 130s;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Request-Id $request_id;
  }
  location / { root /usr/share/nginx/html; try_files $uri $uri/ /index.html; }
}
